server:
  port: 80 #\u4E3A\u4E86\u4EE5\u540E\u8BBF\u95EE\u9879\u76EE\u4E0D\u7528\u5199\u7AEF\u53E3\u53F7
   context-path: /#\u4E3A\u4E86\u4EE5\u540E\u8BBF\u95EE\u9879\u76EE\u4E0D\u7528\u5199\u9879\u76EE\u540D
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/urp?useUnicode=true&characterEncoding=utf-8  #\u89E3\u51B3\u4E2D\u6587\u4E71\u7801\u7684\u95EE\u9898
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update  #\u6570\u636E\u5E93\u540C\u6B65\u4EE3\u7801
    show-sql: true      #dao\u64CD\u4F5C\u65F6\uFF0C\u663E\u793Asql\u8BED\u53E5
